language: ruby
rvm:
  - 2.4.2
env:
  - RAILS_VERSION=5.1.4
addons:
  postgresql: '9.5'
services:
  - postgresql
before_script:
  - psql -c 'create database evendy_api_test;' -U postgres  
env:
  - RAILS_ENV=test
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec
